# 主界面文本
ui.title=我的应用程序
ui.menu.file=文件
ui.menu.edit=编辑
ui.menu.view=视图
ui.menu.help=帮助

# tab Text
tab.orderManagement=订单管理
tab.craftManagement=工艺管理
tab.equipmentManagement=设备管理
tab.jobPlan=作业计划
tab.jobScheduling=作业排产
tab.mainPage=主页
tab.parameterSetting=参数设置

# 按钮文本
button.setCraftNo=设置工艺编号
button.setSchedulingPeriod=设置排产周期
button.generateJobplan=生成作业计划
button.start=开始
button.stop=停止
button.cancel=取消
button.save=保存
button.load=加载
button.export=导出
button.qryJobPlan=查询作业计划 
button.startOpt=开始优化


# 标签文本
label.welcome=欢迎使用应用程序
label.status=状态: 就绪
label.progress=进度:
label.result=结果:
label.theme=群智排
label.orderList=生产订单列表
label.craftList=加工工艺列表
label.craftDetList=工艺明细
label.equipmentList=设备列表
llabel.theme=群智排
label.version=版本:
label.workshop=车间:
label.processDescription=工艺描述:
label.operationName=工序名称:
label.operationSequence=工序顺序:
label.equipmentName=设备名称:
label.operationTime=加工时间:
label.equipmentSupplier=设备供应商:
label.equipmentCode=设备编号:
label.purchaseTime=购买时间:
label.memo=备注:
label.optimizationObjective=OO:
label.optimalObjectiveValue=最优目标值:
label.optimizedSequenceValue=最优序列:
label.optimizationAlgorithm=优化算法:
label.welcome=欢迎使用
label.status=状态: Ready
label.progress=进度:
label.result=结果:
label.messageDisplayArea=消息
label.algorithmRunTime=运行时间:
label.popSize=种群大小:
label.evaluationCount=评估次数:
label.runTimes=运行次数:
label.optimizationObjVal=最优目标值
label.optimizationSequence=最优序列
label.schedulingCycle=排产周期:
label.algorithmName=算法名称
label.KPI=关键性能指标
label.msgArea=显示区
label.sum=共
label.recordTip=条记录
label.startTime=开始时间:
# 菜单项文本
menu.file.sys=系统
menu.file.help=帮助
menu.file.new=新建
menu.file.open=打开
menu.file.save=保存
menu.file.exit=退出
menu.edit.copy=复制
menu.edit.paste=粘贴
#下拉框文本
dropdown.noCraftData=暂无工艺数据.
dropdown.dataToBeLoaded=待加载数据

# 对话框文本
dialog.confirm=确认
dialog.cancel=取消
dialog.save=保存
dialog.load=加载
dialog.operationTip=操作提示
dialog.operationCompleted=操作完成
dialog.craftAddedSuccess=加工工艺已成功插入数据库.
dialog.craftUpdatedSuccess=工艺修改成功.
dialog.orderCraftSettingSuccess=工艺设置成功
dialog.orderCraftSettingFailure=设置工艺失败
dialog.scheduleGeneratedSuccess=生成作业计划成功.
dialog.settingSuccess=设置成功.
dialog.modificationExceptionDetails=修改异常详情:
dialog.FailureConnectDB=数据库连接失败.
dialog.Required=不能为空.
dialog.invalidInput=输入无效.
dialog.verifyODBC=请检查ODBC配置.
dialog.insertFailed=增加失败:
dialog.deleteFailed=删除失败:
dialog.modificationFailed=修改失败:
dialog.modificationSuccess=修改成功
dialog.deleteExceptionDetail=删除异常详情:
dialog.error=错误
dialog.noProcessData=暂无工艺数据
dialog.loadFailed=加载失败
dialog.loadCraftListFailed=加载工艺列表失败:
dialog.loadEqListFailed=加载设备列表失败:
dialog.processDetailAddedSuccess=工序添加成功
dialog.processDetailDeleted=已成功删除
dialog.processSeqGreaterThan0=工序顺序必须大于0
dialog.confirmToDelProDetail=确定要删除工艺明细记录，ID为
dialog.confirmToDel=确认删除
dialog.selectDelProDetailTip=请先在工艺明细列表中选择要删除的记录
dialog.inputSchedulingPeriod=请输入排产周期
dialog.jobPlanGeneratedTip=所选订单记录状态是已经生成作业计划，请重新选择
dialog.selectOrderRecordTip=请选择要生成作业计划的订单记录
dialog.selectRecordTip=请先在列表中选择要操作的记录


#图像
image.src=./navigator_cn.jpg

# 错误消息
error.file_not_found=文件未找到
error.invalid_format=格式无效
error.network_error=网络连接错误


#db
table.order.name=生产订单表
table.equipment.name=加工设备表
table.process.name=工序表
table.jobPlan.name=作业计划表
table.processDetailEquipment.name=工艺明细设备表
table.processMaster.name=加工工艺表
table.processRouteDetail.name=加工工艺流程表

field.order.ID=ID
field.order.OrderNo=订单编号
field.order.ProductName=产品名称
field.order.ProcessCode=加工工艺编号
field.order.Quantity=产品数量
field.order.DeliveryDate=交付日期
field.order.CustomerName=客户名称
field.order.CustomerPhone=客户电话
field.order.OrderStatus=订单状态
field.order.SchedulingCycle=排产周期
field.order.Remarks=备注
field.order.ModifyTime=修改时间
field.order.CreateTime=创建时间

field.Equipment.ID=ID
field.Equipment.EquipmentName=设备名称
field.Equipment.EquipmentCode=设备编号
field.Equipment.ProductionCapacity=生产能力
field.Equipment.OriginalValue=原值
field.Equipment.Supplier=设备供应商
field.Equipment.PurchaseDate=购买日期
field.Equipment.Remarks=备注
field.Equipment.EquipmentAlias=设备别名
field.Equipment.ProductionWorkshop=生产车间

field.Process.ID=ID
field.Process.ProcessCode=工序编号
field.Process.ProcessName=工序名称
field.Process.Remarks=备注

field.OperationPlan.ID=ID
field.OperationPlan.OrderNo=订单编号
field.OperationPlan.ProcessCode=加工工艺编号
field.OperationPlan.ProcessSeq=工序顺序
field.OperationPlan.EquipmentName=设备名称
field.OperationPlan.ProcessName=工序名称
field.OperationPlan.ProcessTime=加工时间
field.OperationPlan.StartTime=开始时间
field.OperationPlan.EndTime=结束时间
field.OperationPlan.WorkTeam=班组
field.OperationPlan.OperationSeq=加工顺序
field.OperationPlan.EquipmentIDSet=设备ID集
field.OperationPlan.ProcessTimeSet=加工时间集
field.OperationPlan.EquipmentNameSet=设备名称集

field.PDE.ID=ID
field.PDE.ProcessDetailID=工艺明细ID
field.PDE.EquipmentID=设备ID
field.PDE.EquipmentName=设备名称
field.PDE.ProcessTime=加工时间
field.PDE.Remarks=备注
field.PDE.CreateTime=创建时间

field.ProcessMaster.ID=ID
field.ProcessMaster.ProcessCode=加工工艺编号
field.ProcessMaster.ProcessDesc=加工工艺描述
field.ProcessMaster.Product=产品
field.ProcessMaster.Version=版本号
field.ProcessMaster.WorkshopType=车间类型
field.ProcessMaster.Creator=创建者
field.ProcessMaster.CreateTime=创建时间
field.ProcessMaster.Modifier=修改者
field.ProcessMaster.ModifyTime=修改时间

field.PRD.ID=ID
field.PRD.ProcessCode=加工工艺编号
field.PRD.ProcessName=工序名称
field.PRD.ProcessSeq=工序顺序
field.PRD.ProcessCreateTime=创建时间
#State
state.orderStaus=已经生成作业计划
state.schedulingRunStateEnd=排产优化完毕
state.schedulingRunStateBegin=开始调用排产引擎
#windwo
window.modifyOrder =修改订单
window.modifyCraft=修改工艺
window.modifyEquipment =修改设备  
